package coffeepartner.capt.plugin.api;

import coffeepartner.capt.plugin.api.util.RelativeDirectoryProvider;

import java.io.IOException;

public interface OutputProvider {

    /**
     * Ensure the directory exists, unique for every plugin.
     *
     * @param type type
     * @return dir
     */
    RelativeDirectoryProvider getProvider(Type type);

    /**
     * Remove all content of this plugin.
     *
     * @throws IOException if deleting failed.
     */
    void deleteAll() throws IOException;


    enum Type {
        /**
         * the generated byte-code in this dir will also be added to the transform pipeline as a
         * EXTERNAL_LIBRARIES stream.
         * <p>
         * Write class file in sub directory according to its package!
         * MUST NOT write jar or other strange things!
         */
        CLASS,
        /**
         * Any change in this dir after build will led next build to full mode.
         */
        CACHE,
        /**
         * Don't depends on files on it from last build.
         */
        TEMP
    }
}
