package com.dieyidezui.lancet.plugin.api;

import com.dieyidezui.lancet.plugin.api.util.RelativeDirectoryProvider;

import java.io.IOException;

public interface OutputProvider {

    /**
     * Ensure the dir exists, the generated byte-code in this dir will also be added to the transform pipeline as a
     * EXTERNAL_LIBRARIES stream.
     * Write class file in sub directory according to its package!
     * MUST NOT write jar or other strange things!
     *
     * @return dir
     */
    RelativeDirectoryProvider getClassProvider();

    /**
     * Ensure the dir exists, just temporary dir.
     * Don't depends on files on it from last build.
     *
     * @return dir
     */
    RelativeDirectoryProvider getTemporaryProvider();

    /**
     * Ensure the dir exists, the cache will be reused by next builds.
     * Any change in this dir after build will led next build to full mode.
     *
     * @return dir
     */
    RelativeDirectoryProvider getCacheProvider();

    /**
     * Remove all content of this plugin.
     *
     * @throws IOException if deleting failed.
     */
    void deleteAll() throws IOException;
}
