package com.dieyidezui.lancet.plugin.api;

import java.io.File;

public interface OutputProvider {

    /**
     * Ensure the dir exists, the generated byte-code in this dir will also be added to the transform pipeline as a
     * EXTERNAL_LIBRARIES stream.
     * Write class file in sub directory according to its package!
     * MUST NOT write jar or other strange things!
     *
     * @return dir
     */
    File getOutputClassRootDir();

    /**
     * Ensure the dir exists, just temporary dir.
     * Don't depends on files on it from last build.
     *
     * @return dir
     */
    File getTemporaryDir();

    /**
     * Ensure the dir exists, the cache will reuse by next builds.
     * Any change in this dir after build will led next build to full mode.
     *
     * @return dir
     */
    File getCacheDir();
}
